// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UniversityOfNottinghamAPI.Database;

#nullable disable

namespace UniversityOfNottinghamAPI.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UniversityOfNottinghamAPI.Models.OutputModels.DocumentOutput", b =>
                {
                    b.Property<string>("Document_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Approval_Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Author_Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Author_User_ID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Document_Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("File_Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Last_Accessed_User_ID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Last_Accessed_User_Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Last_Modified_User_ID")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Last_Modified_User_Name")
                        .IsRequired()
                        .HasColumnType("varchar(50)");

                    b.HasKey("Document_ID");

                    b.ToTable("DocumentOutputs");
                });

            modelBuilder.Entity("UniversityOfNottinghamAPI.Models.OutputModels.UsersOutput", b =>
                {
                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
